{{- if .Values.otel.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otel.collectorServiceName }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
      batch:
    exporters:
      azuremonitor:
        instrumentation_key: ""
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [azuremonitor]
{{- end }}
